import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ForestModel1(props) {
  const { nodes, materials } = useGLTF("../forest1.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-2348.17, -387.05, 2955.73]}
            rotation={[-Math.PI, -0.83, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.birdhouse1_BirdHouse_0.geometry}
              material={materials.BirdHouse}
            />
          </group>
          <group
            position={[-1021.75, 59.41, 3863.79]}
            rotation={[-Math.PI, -1.24, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rocking_chair_RockingChair_SmallStatue_0.geometry}
              material={materials.RockingChair_SmallStatue}
            />
          </group>
          <group
            position={[732.87, -368.3, -3667.9]}
            rotation={[-Math.PI, 1.5, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lightstand_BirdHouse_0.geometry}
              material={materials.BirdHouse}
            />
          </group>
          <group position={[2816, -77.66, -667.08]} rotation={[0, 0.29, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.little_statue_RockingChair_SmallStatue_0.geometry}
              material={materials.RockingChair_SmallStatue}
            />
          </group>
          <group position={[816.23, 85.37, -198.46]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ground_surface_Trans_RockGrass_Snacks_0.geometry}
              material={materials.Trans_RockGrass_Snacks}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ground_surface_StoneWall_0.geometry}
              material={materials.StoneWall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ground_surface_Road_0.geometry}
              material={materials.Road}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ground_surface_Dirt_road_transition_0.geometry}
              material={materials.Dirt_road_transition}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ground_surface_GroundTex_Grass_0.geometry}
              material={materials.GroundTex_Grass}
            />
          </group>
          <group position={[816.23, 85.37, -198.46]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fill_bottom_plane_Road_0.geometry}
              material={materials.Road}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Water_well_BambooWaterSource_0.geometry}
              material={materials.BambooWaterSource}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Water_well_PrayRock_0.geometry}
              material={materials.PrayRock}
            />
          </group>
          <group
            position={[767.02, 390.42, -100.86]}
            rotation={[-3.1, -1.18, -3.09]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.outdoor_table_chairs_Pillows_Outside_0.geometry}
              material={materials.Pillows_Outside}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.outdoor_table_chairs_Dark_Wood_0.geometry}
              material={materials.Dark_Wood}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rocks_Basic_Rock_0.geometry}
              material={materials.Basic_Rock}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rocks_StoneWall_0.geometry}
              material={materials.StoneWall}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rocks_Closet_Rock_Cloth_0.geometry}
              material={materials.Closet_Rock_Cloth}
            />
          </group>
          <group position={[2813.99, 85.37, 1669.43]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ricksha_Riksha_0.geometry}
              material={materials.Riksha}
            />
          </group>
          <group position={[2829.44, 85.37, 848.75]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arch_Arch_0.geometry}
              material={materials.Arch}
            />
          </group>
          <group
            position={[853.79, 434, 2853.11]}
            rotation={[-0.01, 0.2, -0.1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.long_bench_Big_Bench_0.geometry}
              material={materials.Big_Bench}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Default_Material_0.geometry}
              material={materials.Default_Material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Wood_Types_0.geometry}
              material={materials.Wood_Types}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Windows_HouseProps_0.geometry}
              material={materials.Windows_HouseProps}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Roofing_slate_0.geometry}
              material={materials.Roofing_slate}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Dark_Wood_0.geometry}
              material={materials.Dark_Wood}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.house_and_interior_Closet_Rock_Cloth_0.geometry}
              material={materials.Closet_Rock_Cloth}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.leafs_m_cherryblossom_0.geometry}
              material={materials.m_cherryblossom}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.trashcans_Trashcan_0.geometry}
              material={materials.Trashcan}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_edges_EdgeGrass_Plants_0.geometry}
              material={materials.EdgeGrass_Plants}
            />
          </group>
          <group
            position={[523.35, 186.36, -145.27]}
            rotation={[3.1, 0.98, -3.09]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.doghouse_Wood_Types_0.geometry}
              material={materials.Wood_Types}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.doghouse_Dark_Wood_0.geometry}
              material={materials.Dark_Wood}
            />
          </group>
          <group
            position={[594.5, 193.89, -129.81]}
            rotation={[-Math.PI, 0.63, 3.06]}
            scale={1.11}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.dog_Dog_0.geometry}
              material={materials.material}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.books_n_cards_Cards_Books_Leakage_0.geometry}
              material={materials.Cards_Books_Leakage}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.dirt_on_house_Cards_Books_Leakage_0.geometry}
              material={materials.Cards_Books_Leakage}
            />
          </group>
          <group position={[2813.59, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_1.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_2.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_3.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_4.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_5.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_6.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_7.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_8.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_9.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_10.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_11.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_12.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_13.geometry}
              material={materials.Grass_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.grass_Grass_Main_0_14.geometry}
              material={materials.Grass_Main}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.trees_Default_Material_0.geometry}
              material={materials.Default_Material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.trees_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.trees_bark_0.geometry}
              material={materials.bark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.trees_m_cherryblossom_0.geometry}
              material={materials.m_cherryblossom}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Basic_Rock_0.geometry}
              material={materials.Basic_Rock}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Wood_Types_0.geometry}
              material={materials.Wood_Types}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Dark_Wood_0.geometry}
              material={materials.Dark_Wood}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Rock_Letters_0.geometry}
              material={materials.Rock_Letters}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Roof_lavatory_0.geometry}
              material={materials.Roof_lavatory}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_Trashcan_0.geometry}
              material={materials.Trashcan}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lavatory_m_cherryblossom_0.geometry}
              material={materials.m_cherryblossom}
            />
          </group>
          <group position={[2816.08, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.weed_EdgeGrass_Plants_0.geometry}
              material={materials.EdgeGrass_Plants}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.weed_Weeds_0.geometry}
              material={materials.Weeds}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.dirt_Cards_Books_Leakage_0.geometry}
              material={materials.Cards_Books_Leakage}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.praying_rock_PrayRock_0.geometry}
              material={materials.PrayRock}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.praying_rock_Rock_Letters_0.geometry}
              material={materials.Rock_Letters}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.praying_rock_Closet_Rock_Cloth_0.geometry}
              material={materials.Closet_Rock_Cloth}
            />
          </group>
          <group position={[2813.99, 85.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.tea_set_wine_bottles_Trans_RockGrass_Snacks_0.geometry
              }
              material={materials.Trans_RockGrass_Snacks}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../forest1.glb");

export default ForestModel1